# Travis example for Identifier created by Rafael Garibotti
os: linux
dist: xenial
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr

install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"

script:
  - make all
after_success:
  - ./commiter.sh
