# Travis example for Identifier created by Rafael Garibotti
os: linux
dist: xenial
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
  
jobs:
  include:
    - stage: tests
      script: 
      - make all
    - stage: deploy
        deploy:
          provider: script
          script: bash commiter.sh
          on:
            branch: warmup-travis-test
            tags: true