# Travis example for Identifier created by Rafael Garibotti
os: linux
dist: xenial
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"

script:
  - make all
#jobs:
#  include:
#    - stage: tests
#      script:
#      - make all
#    - stage: deploy
#      deploy:
#        provider: releases
#        cleanup: false
#        token: $GITHUB_TOKEN
#        file: coverage/**
#        on:
#          branch: warmup
