# Travis example for Identifier created by Rafael Garibotti

language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
  
jobs:
  include:
    - stage: tests
      script: 
      - make all
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: warmup