# Travis example for Identifier created by Rafael Garibotti
os: linux
dist: xenial
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr

install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"

script:
  - make all
  - mkdir deploy && mv converage deploy/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: deploy
  on:
    branch: warmup
