# Travis example for Identifier created by Rafael Garibotti
os: linux
dist: xenial
language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install gcovr
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck

install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"

script:
  - make all
