# Travis example for Identifier created by Rafael Garibotti

sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcov
      - gcovr
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - make clean compile UnitTests
  - make clean compile valgrind
  - make clean addressSanitizer
  - make clean cov